name: Test Kluctl Action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Kluctl (latest)
      uses: ./  # Use the action from the current repo
      with:
        version: latest

    - name: Verify kluctl installation
      run: kluctl version
      shell: bash